# Generated by Django 4.2.6 on 2023-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_description', models.TextField(max_length=100)),
                ('blog_content', models.TextField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
