# Generated by Django 4.2.6 on 2023-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='blog_description',
            field=models.TextField(),
        ),
    ]
